INSERT INTO gost(ime,prezime,mail,password,registrovan) VALUES ('Milos','Nisic','gost@gost.com','gost','1')
INSERT INTO gost(ime,prezime,mail,password,registrovan) VALUES ('Djura','Djuric','gost2@gost2.com','gost2','1')
INSERT INTO restoran(naziv,opis,drzava,grad,ulica) VALUES('restoran1', 'opis', 'drzava', 'grad', 'ulica')
INSERT INTO restoran(naziv,opis,drzava,grad,ulica) VALUES('restoran2', 'opis', 'drzava', 'grad', 'ulica')
INSERT INTO kuvar(ime,prezime,mail,password,velicina_odece,velicina_obuce, registrovan, restoran_id) VALUES ('Stefan','Ceranic','kuv@kuv.com','kuv','XL','br43', '1', 1)
INSERT INTO konobar(ime,prezime,mail,password,velicina_odece,velicina_obuce,registrovan, restoran_id) VALUES ('Milan','Gvero','kon@kon.com','kon','L','br42','1', 1)
INSERT INTO menadzer_sistema(ime,prezime,mail,password,registrovan) VALUES ('ms','ms','ms@ms.com','ms','1')
INSERT INTO menadzer_restorana(ime,prezime,mail,password,zaposlen,registrovan, restoran_id) VALUES ('men','men','men@men.com','men',1,'1',1)
INSERT INTO menadzer_restorana(ime,prezime,mail,password,zaposlen,registrovan) VALUES ('men2','men2','men2@men2.com','men2',0,'1')
INSERT INTO sanker(ime,prezime,mail,password,velicina_odece,velicina_obuce, registrovan, restoran_id) VALUES ('Pera','Peric','san@san.com','san','XL','br46','1', 1)
INSERT INTO restorani_i_menadzeri(Restoran_ID,Menadzer_restorana_ID) VALUES (1,1)
INSERT INTO restorani_i_kuvari(Restoran_ID,Kuvar_ID) VALUES (1,1)
INSERT INTO restorani_i_konobari(Restoran_ID,Konobar_ID) VALUES (1,1)
INSERT INTO restorani_i_sankeri(Restoran_ID,Sanker_ID) VALUES (1,1)
INSERT INTO jelo(naziv,opis,cena,ocena) VALUES ('Pljeskavica','Opis',150,5)
INSERT INTO jelo(naziv,opis,cena,ocena) VALUES ('Piletina','Opis',200,4)
INSERT INTO pice(naziv,opis,cena,ocena) VALUES ('Caj','Opis',80,4)
INSERT INTO jelovnik(Restoran_ID,Jelo_ID) VALUES (1,1)
INSERT INTO jelovnik(Restoran_ID,Jelo_ID) VALUES (1,2)
INSERT INTO karta_pica(Restoran_ID,Pice_ID) VALUES (1,1)
INSERT INTO ponudjac(ime,prezime,mail,password,registrovan) values('Petar','Petrovic','pon@pon.com','pon','0')
INSERT INTO ponudjac(ime,prezime,mail,password,registrovan) values('Jova','Jovic','pon2@pon2.com','pon2','0')

